global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "ratelimiter"
    static_configs:
      - targets:
          - "ratelimiter-1:9090"
          - "ratelimiter-2:9090"
        labels:
          service: "rate-limiter"

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]